### ISSUE TITLE
Файл манифеста отсутствует

### ISSUE THREAD

**Issue by rusonic** [7l1nky/Yaklass-dzhelper-cracked#1]
![изображение](https://user-images.githubusercontent.com/93402361/197374815-8a9cc209-a93d-44b0-a310-6e1219ea1614.png)

**Comment by 7l1nky** [comment]
1) распаковать zip папку куда либо
2) вкючить 
![image](https://user-images.githubusercontent.com/93197615/197388742-73e8f0ff-a6a9-4301-9391-8f42b9f5b109.png)
3) загрузить расширение 
![image](https://user-images.githubusercontent.com/93197615/197388767-fcf305bf-1802-40eb-8424-124946411af9.png)

**Comment by rusonic** [comment]
дак я это и сделала :/

**Comment by 7l1nky** [comment]
попробуй открыть скачанную zip папку и из нее кинуть папку "Yaklass-pasta-dzhelper-main" на рабочий стол.
